<?php

namespace App\Http\Controllers;

use Inertia\Inertia;
use Inertia\Response;

class PrestasiController extends Controller
{
    private $daftarKejuaraan = [
        ["Pentas PAI SMK 2017 Wilayah IV Provinsi Jawa Barat", "Juara 1 untuk Bidang Lomba Marawis"],
        ["Lomba Pasanggiri Riksa Budaya Sunda UPI se-Jawa Barat 2017", "Juara 1 Bidang Lomba Lagu Pasanggiri Pupuh"],
        ["FLS2N SMK Tingkat Provinsi Jawa Barat 2017", "Juara 1 Bidang Lomba TARI TRADISIONAL SMK SENI"],
        ["RUKIBRA SMA/SMK SE-JABAR OPEN 2017", "Juara Harapan Utama 1 Bidang Lomba RUKIBRA"],
        ["Pasanggiri Degung Tingkat Jabar & Banten 2017", "juara 3 Bidang Lomba Pasanggiri Degung"],
        ["DJAMOE 36 Seni EUPHORIA SE-JAWA BARAT 2017", "Juara 3 Lomba Film Pendek "],
        ["LKBB SMA/SMK di SMK WIDYA DIRGANTARA SE-JABAR OPEN 2018", "Juara Purwa 3  Bidang Lomba LKBB"],
        ["LKBB SMA/SMK di SMK WIDYA DIRGANTARA SE-JABAR OPEN 2018", "Juara Kostum Terbaik  Bidang Lomba LKBB"],
        ["LKBB BRIGANTARA EVENT 4 se-Jawa Barat Open 2018", "Juara 2 Mula Bidang Lomba LKBB"],
        ["GKSN FAI Tingkat Nasional UNINUS 2018", "Juara 2 Bidang Lomba Nasyid"],
        ["GKSN FAI Tingkat Nasional UNINUS 2018", "Juara Harapan 1 Bidang Lomba Marawis"],
        ["RUKIBRA SMA/SMK SE-JABAR OPEN 2018", "Juara Utama 2 Bidang Lomba RUKIBRA"],
        ["BENTANG PILIHAN AKTV  SE-JAWA BARAT", "Juara 1 Bidang Lomba Lagu POP SUNDA"],
        ["Pucuk CoolJaam Festival se-Jabar 2018", "Juara 3 Bidang Lomba Ektrakurikuler Happy Dance"],
        ["Festival Band Pelajar SMA/SMK se-Kota Bandung Polda Jabar 2018", "Juara 2 Bidang Lomba Band"],
        ["KALAM XII (Kreativitas dan Lomba Anak Muslim) Se-Jabar 2019", "Memperoleh juara Favorit bidang lomba Nasyid"],
        ["KALAM XII (Kreativitas dan Lomba Anak Muslim) Se-Jabar 2019", "Memperoleh juara 2 bidang lomba Nasyid"],
        ["Lomba Rukibra tingkat SMA/SMK/MA  Se-Jabar Open 2019", "Memperoleh juara 1 Madya Lomba Rukibra "],
        ["Lomba Regu Pengibar Bendera SMA/SMK  se- Jabar Open 2019", "Memperoleh juara Potensial 3 dalam bidang lomba Rukibra"],
        ["Gebyar PAI SMK Se - Kota Bandung 2019", "Memperoleh juara 2 bidang  lomba Acapella"],
        ["Gebyar PAI SMK Se - Kota Bandung 2019", "Memperoleh juara 1 bidang  lomba Marawis"],
        ["Gebyar Pentas PAI SMK se- Jabar 2019", "Memperoleh Juara 1 Nasyid Acapella se- Jawa Barat"],
        ["School Ambasador 2019", "Memperoleh Juara 1 Tingkat Nasional"],
        ["Ajang Kreasi Anak Bangsa Piala Walikota 2019", "Memperoleh juara Utama 1 dalam bidang lomba Rukibra"],
        ["FLS2N Tingkat Kota Bandung 2019", "Memperoleh juara 1 dalam bidang lomba Solo Gitar klasik"],
        ["FLS2N Tingkat Nasional  2019", "Memperoleh juara 1 dalam bidang lomba Solo Gitar klasik"],
        ["FLS2N Tingkat Kota Bandung 2019", "Memperoleh juara 1 dalam bidang lomba Solo vocal"],
        ["FLS2N Tingkat Kota Bandung 2019", "Memperoleh juara 1 dalam bidang lomba Tari Tradisional"],
        ["FLS2N Tingkat Kota Bandung 2019", "Memperoleh juara 1 dalam bidang lomba Musik Tradisional"],
        ["FLS2N Tingkat Jawa Barat  2019", "Memperoleh juara 2 dalam bidang lomba Teater"],
        ["FLS2N Tingkat Jawa Barat  2019", "Memperoleh juara 2 dalam bidang lomba Musik Tradisional"],
        ["FLS2N Tingkat Jawa Barat  2019", "Memperoleh juara 1 dalam bidang lomba Tari Tradisional"],
        ["Festival Film Surabaya Tingkat Nasional 2019", "Memperoleh juara 3 Kategori Film Dokumenter"],
        ["HUT Pramuka ke 58 se Kwatir cabang Kota Bandung 2019", "Memperoleh juara 2 dalam bidang lomba Tari"],
        ["HUT Pramuka ke 58 se Kwatir cabang Kota Bandung 2019", "Memperoleh juara 2 dalam bidang lomba perkusi karawitan"],
        ["Festival film pelajar Pelita Perdamaian Cirebon Tingkat Nasional", "Memperoleh juara 3 dalam bidang Film Pendek"],
        ["Jabar OTOFEST Tingkat Jabar 2019", "Memperoleh juara 2 dalam bidang lomba Band"],
        ["Parahyangan Berkibar Berbaris dan Kibar Bendera Tingkat Jabar  2019", "Memperoleh juara  Harapan Utama 3 dalam bidang lomba Rukibra"],
        ["Parahyangan Berkibar Berbaris dan Kibar Bendera Tingkat Jabar  2019", "Memperoleh juara  Harapan Utama 1 dalam bidang lomba Rukibra"],
        ["Pasanggiri Degung Piala R.A.A Wiranatakusumah Tingkat Jabar 2019", "Memperoleh juara 3 dalam bidang lomba Degung"],
        ["Rukibra (Regu Pengibar Bendera) Purna Paskibraka Indonesa Se- Jabar 2019", "Memperoleh juara 3 dalam bidang lomba Anggana Sekar"],
        ["Pasanggiri Seni Sunda XV Se Jabar Lingkung Seni UNPAS 2020", "Memperoleh juara 1 dalam bidang lomba Rampak Jaipong"],
        ["Pasanggiri Seni Sunda XV Se Jabar Lingkung Seni UNPAS 2020", "Memperoleh juara Utama 2 dalam bidang lomba Rukibra"],
        ["Jabar From Home Challenge 2020", "Memperoleh juara 1 dalam bidang lomba Gerakan Sosial (Social Movement)"],
        ["Jabar Islamic Book Fair 2019", "Memperoleh juara 3 dalam bidang lomba Nasyid"],
        ["FLS2N Tingkat Kota Bandung 2021", "Memperoleh juara 1 dalam bidang lomba Solo Gitar klasik"],
        ["FLS2N Tingkat Kota Bandung 2021", "Memperoleh juara 1 dalam bidang lomba Solo vocal"],
        ["FLS2N Tingkat Kota Bandung 2021", "Memperoleh juara 1 dalam bidang lomba Tari Tradisional"],
        ["FLS2N Tingkat Kota Bandung 2021", "Memperoleh juara 1 dalam bidang lomba Musik Tradisional"],
        ["FLS2N Tingkat Kota Bandung 2021", "Memperoleh juara 1 dalam bidang lomba Cipta Lagu"],
        ["FLS2N Tingkat Jawa Barat  2021", "Memperoleh juara 1 dalam bidang lomba Solo Gitar klasik"],
        ["FLS2N Tingkat Jawa Barat  2021", "Memperoleh juara 2 dalam bidang lomba Solo vocal"],
        ["FLS2N Tingkat Jawa Barat  2021", "Memperoleh juara 1 dalam bidang lomba Musik Tradisional"],
        ["FLS2N Tingkat Jawa Barat  2021", "Memperoleh juara 1 dalam bidang lomba Monolog"],
        ["FLS2N Tingkat Kota Bandung 2022", "Memperoleh juara 1 dalam bidang lomba Tari Tradisional"],
        ["FLS2N Tingkat Kota Bandung 2022", "Memperoleh juara 1 dalam bidang lomba Musik Tradisional"],
        ["FLS2N Tingkat Jawa Barat  2022", "Memperoleh juara 1 dalam bidang lomba Cipta Lagu"],
        ["FLS2N Tingkat Jawa Barat  2022", "Memperoleh juara 2 dalam bidang lomba Teater"],
        ["FLS2N Tingkat Jawa Barat  2022", "Memperoleh juara 1 dalam bidang lomba Musik Tradisional"],
        ["FLS2N Tingkat Nasional  2022", "Memperoleh juara 2 dalam bidang lomba Solo Gitar klasik"],
        ["FLS2N Tingkat Nasional  2022", "Memperoleh juara 1 dalam bidang lomba Musik Tradisional"],
        ["FLS2N Tingkat Kota Bandung 2023", "Memperoleh juara 1 dalam bidang lomba Cipta Lagu Film Fiksi"],
        ["FLS2N Tingkat Jawa Barat  2023", "Memperoleh juara 1 dalam bidang lomba Tari kreasi"],
        ["FLS2N Tingkat Jawa Barat  2023", "Memperoleh juara 1 dalam bidang lomba Cipta Lagu"],
        ["FLS2N Tingkat Jawa Barat  2023", "Memperoleh juara 2 dalam bidang lomba Musik kreasi"],
        ["FLS2N Tingkat Jawa Barat  2023", "Memperoleh juara 1 dalam bidang lomba Tari kreasi"],
        ["FLS2N Tingkat Jawa Barat  2023", "Memperoleh juara 1 dalam bidang lomba Solo Gitar klasik"],
        ["FLS2N Tingkat Jawa Barat  2023", "Memperoleh juara 2 dalam bidang lomba solo vokal"],
        ["FLS2N Tingkat Jawa Barat  2023", "Memperoleh juara 1 dalam bidang lomba  Monolog"],
        ["FLS2N Tingkat Nasional  2023", "Memperoleh juara 2 dalam bidang lomba Solo Gitar klasik"],
        ["FLS2N Tingkat Nasional  2023", "Memperoleh juara  harapan 1 dalam bidang lomba Tari kreasi"],
        ["FLS2N Tingkat Nasional  2023", "Memperoleh juara 2 dalam bidang lomba  Monolog"],
        ["FLS2N Tingkat Kota Bandung 2024", "Memperoleh juara 1 dalam bidang lomba Musik kreasi"],
        ["FLS2N Tingkat Kota Bandung 2024", "Memperoleh juara  1 dalam bidang lomba Tari kreasi"],
        ["FLS2N Tingkat Kota Bandung 2024", "Memperoleh juara 1 dalam bidang lomba Solo Gitar"],
        ["FLS2N Tingkat Kota Bandung 2024", "Memperoleh juara 1 dalam bidang lomba Solo Vokal"],
        ["FLS2N Tingkat Kota Bandung 2024", "Memperoleh juara 1 dalam bidang lomba Cipta Lagu"],
        ["FLS2N Tingkat Kota Bandung 2024", "Memperoleh juara 1 dalam bidang lomba Monolog"],
        ["FLS2N Tingkat Kota Bandung 2024", "Memperoleh juara 1 dalam bidang lomba Film Fiksi"],
    ];

    public function show(): Response {
        return Inertia::render('prestasi/PrestasiSekolah', ['daftarKejuaraan' => $this->daftarKejuaraan]);
    }
}
